### ISSUE TITLE
Create Bug Report Template

### ISSUE THREAD

**Issue by demilolu** [embrace-call-for-code/fairchange#55]
### Background on the problem the feature will solve/improved user experience
Create a Bug Report Template for Fair Change

### Describe the solution you'd like
Add a .md file to the Github Issues Templates to create a new template

### Tasks 

1. copy the text in the following link:  https://raw.githubusercontent.com/Call-for-Code-for-Racial-Justice/Hacktoberfest/main/.github/ISSUE_TEMPLATE/bug-report-template.md

2. Create a new file in the Fair Change folder: [.github/ ISSUE_TEMPLATE
](https://github.com/Call-for-Code-for-Racial-Justice/FairChange/tree/main/.github/ISSUE_TEMPLATE)
3. Paste the copied text from above into file 
4. name the file:  bug_report_template.md
5. commit the change to your branch and create a pull request 

### Acceptance Criteria
- Bug Report template file is in Fair Change [Issue Template folder ](https://github.com/Call-for-Code-for-Racial-Justice/FairChange/tree/main/.github/ISSUE_TEMPLATE)
- As a user, when I click "new issue" in the Fair Change repository I see an option for the Bug Report Template

**Comment by rtkimz** [comment]
I would like to work on this issue.

**Comment by demilolu** [comment]
hi @rtkimz - it's yours.

**Comment by demilolu** [comment]
@rtkimz do you have a PR for this issue?

**Comment by demilolu** [comment]
closed by #58
